In [2]:
import transformers
from torch import functional as F

/mnt/hdd/spaces/santapo/anaconda3/envs/hackathon/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from torch.nn import functional as F

In [4]:
import torch
from transformers import AutoModel, AutoTokenizer

phobert = AutoModel.from_pretrained("vinai/phobert-base")
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

# INPUT TEXT MUST BE ALREADY WORD-SEGMENTED!
sentence = 'Chúng_tôi là những nghiên_cứu_viên .'  

input_ids = torch.tensor([tokenizer.encode(sentence)])

with torch.no_grad():
    features = phobert(input_ids)  # Models outputs are now tuples

## With TensorFlow 2.0+:
# from transformers import TFAutoModel
# phobert = TFAutoModel.from_pretrained("vinai/phobert-base")

Some weights of the model checkpoint at vinai/phobert-base were not used when initializing RobertaModel: ['lm_head.decoder.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [40]:
batch_inputs = torch.concat([input_ids, input_ids], dim=0)
batch_inputs.shape

torch.Size([2, 7])

In [41]:
with torch.no_grad():
    features = phobert(batch_inputs)


In [30]:
word_1 = "false"
input_1 = torch.tensor([tokenizer.encode(word_1)])

word_2 = ""
input_2 = torch.tensor([tokenizer.encode(word_2)])

with torch.no_grad():
    features_1 = phobert(input_1)
    features_2 = phobert(input_2)

F.cosine_similarity(features_1[1], features_2[1])

tensor([0.3267])

In [24]:
["ASLDKFJAL", "AJOSDHFAOSDKJ"].lower()

AttributeError: 'list' object has no attribute 'lower'

In [17]:
import re

re.sub(r'[^\s\wáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệóòỏõọôốồổỗộơớờởỡợíìỉĩịúùủũụưứừửữựýỳỷỹỵđ_]',' ',text)

'Chúng tôi là những nghiên cứu viên 9873  7 '

In [21]:
import nltk
from nltk.corpus import treebank, stopwords
from nltk.tokenize import word_tokenize


sentence = "- Use proficiently kjahgkdsajadsbfksd  Pascal, C, C++, Java, C#, Python programming languages\nPRODUCTS\n- Web Programming (HTML,CSS,JS,JQ)\n- AI programming (mainly computer vision)\n(C++,Python)\n- Deployment AI code (Deepstream , triton,\nrabitMQ, elasticsearch, NCNN,...)"
sentence = re.sub(r'[^\s\wáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệóòỏõọôốồổỗộơớờởỡợíìỉĩịúùủũụưứừửữựýỳỷỹỵđ_]',' ', sentence)
# sentence = "Trung thực, năng động, tự tin, sáng tạo, có tinh thần trách nhiệm cao trong  công việc.\nGiao tiếp tốt, có sẵn mối quan hệ với các hệ thống siêu thị.\nCó khả năng đàm phán thương thuyết với khách hàng.\nThành thạo vi tính văn phòng.\nCó khả năng lãnh đạo nhóm, phát triển cũng như huấn luyện cho nhân viên  cấp dưới.\nCó kinh nghiệm lâu năm trong việc quản lý nhân sự"
# sentence = "Đọc sách. Thư giãn bằng nhạc không lời. Tập thể dục buổi sáng và buổi chiều\nDu lịch và khám phá các miền đất mới. Được học hỏi và train các kỹ năng mới"
tokens = nltk.word_tokenize(sentence)
stop_words = set(stopwords.words('vietnamese'))
# stop_words = set(stopwords.words('english'))

words = [w for w in tokens if w not in stop_words]
sentence = ' '.join(words)
tokens = nltk.word_tokenize(sentence)
stop_words = set(stopwords.words('english'))
print(words)

['Use', 'proficiently', 'kjahgkdsajadsbfksd', 'Pascal', 'C', 'C', 'Java', 'C', 'Python', 'programming', 'languages', 'PRODUCTS', 'Web', 'Programming', 'HTML', 'CSS', 'JS', 'JQ', 'AI', 'programming', 'mainly', 'computer', 'vision', 'C', 'Python', 'Deployment', 'AI', 'code', 'Deepstream', 'triton', 'rabitMQ', 'elasticsearch', 'NCNN']


In [107]:
from difflib import SequenceMatcher
word_1 = "\u2022 An active team member with ability to handle problems individually\n\u2022 Strong communication skills\n\u2022 Fluent in the English language\n\u2022 Experience with using Microsoft office: Word, Excel, PP  \u2022 Hardworking and able to work long hours when necessary"
word_2 = "Microsoft Word Excel"
SequenceMatcher(None, word_2, word_1).ratio()

0.02247191011235955

tensor([0.6684])

In [17]:
features_2[1].shape

torch.Size([1, 768])

In [10]:
F.cosine_similarity(features_1[0], features_2[0])

RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 1

In [10]:
tokenizer.encode(sentence)

[0, 746, 8, 21, 46349, 5, 2]

In [4]:
torch.__version__

'1.11.0+cu113'

In [38]:
tokenizer.encode(word_1, return_tensors="pt")

tensor([[    0, 28138, 55759,  2139,     2]])

In [71]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

model = T5ForConditionalGeneration.from_pretrained("NlpHUST/t5-small-vi-summarization")
tokenizer = T5Tokenizer.from_pretrained("NlpHUST/t5-small-vi-summarization")


src = "Creative and Production \n- Head Ho Chi Minh City, Vietnam September 2011 \n- March 2015 (3 years 7 months) Ho Chi Minh City, Vietnam Mead Johnson Nutrition Management Trainee October 2010 \n- August 2011 (11 months) Ho Chi Minh city"
tokenized_text = tokenizer.encode(src, return_tensors="pt")
model.eval()
summary_ids = model.generate(
                    tokenized_text,
                    max_length=256, 
                    num_beams=5,
                    repetition_penalty=2.5, 
                    length_penalty=1.0, 
                    early_stopping=True
                )
output = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print(output)

Downloading: 100%|██████████| 572/572 [00:00<00:00, 177kB/s]
Downloading: 100%|██████████| 1.12G/1.12G [01:24<00:00, 14.2MB/s]


ImportError: 
T5Tokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment.
